name: pinch_zoom_image_example
description: Demonstrates how to use the pinch_zoom_image plugin.
publish_to: 'none'

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pinch_zoom_image:
    path: ../
  cached_network_image: ^0.5.0

flutter:
  uses-material-design: true
  assets:
   - images/camel.jpg
