name: pinch_zoom_image
description: A widget that makes picture pinch zoom, then return back to initial size and position when released.
version: 0.2.5
author: Youssef Kababe <youssef.kbe@gmail.com>
homepage: https://github.com/YoussefKababe/pinch_zoom_image

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.shatsy.pinchzoomimage
    pluginClass: PinchZoomImagePlugin
